version: '3.8'

services:
  # Сервис базы данных
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
  
  # Сервис бэкенда
  backend:
    build: ./RentalService
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
  
  # Сервис фронтенда
  frontend:
    build: ./rental-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
